version: "3.9"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - network
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - network

  redis:
    container_name: redis_container
    image: redis
    restart: unless-stopped
    command: redis-server --save 20 1 --loglevel warning --requirepass redisPassword --maxmemory 1gb --maxmemory-policy allkeys-lru
    volumes: 
      - redis:/data
    ports:
      - "6379:6379"
    networks:
      - network

  p3x-redis-ui:
    container_name: p3x-redis-ui_container
    image: patrikx3/p3x-redis-ui:latest
    restart: unless-stopped
    volumes: 
      - p3x:/settings
    ports:
      - "7843:7843"
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
    postgres:
    pgadmin:
    redis:
    p3x: